package ChatApp;


/**
* ChatApp/ChatOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Chat.idl
* den 22 mars 2015 kl 12:39 CET
*/

public interface ChatOperations 
{
  boolean post (String name, String message);
  boolean join (ChatApp.ChatCallback objref, String name);
  boolean list (ChatApp.ChatCallback objref);
  boolean quit (ChatApp.ChatCallback objref);
  boolean game (ChatApp.ChatCallback objref, char color);
  boolean plop (ChatApp.ChatCallback objref, int row);
} // interface ChatOperations
